# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocol.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protocol.proto',
  package='gameprotocol.events',
  serialized_pb='\n\x0eprotocol.proto\x12\x13gameprotocol.events\"U\n\x05\x45vent\x12\x11\n\tEventName\x18\x01 \x02(\t\x12\x15\n\rFormatVersion\x18\x02 \x02(\x05\x12\x11\n\tTimestamp\x18\x03 \x02(\x01\x12\x0f\n\x07Message\x18\x04 \x02(\t')




_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='gameprotocol.events.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='EventName', full_name='gameprotocol.events.Event.EventName', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='FormatVersion', full_name='gameprotocol.events.Event.FormatVersion', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Timestamp', full_name='gameprotocol.events.Event.Timestamp', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Message', full_name='gameprotocol.events.Event.Message', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=39,
  serialized_end=124,
)

DESCRIPTOR.message_types_by_name['Event'] = _EVENT

class Event(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EVENT

  # @@protoc_insertion_point(class_scope:gameprotocol.events.Event)


# @@protoc_insertion_point(module_scope)
